{"name": "Залогиненный пользователь может оформить заказ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <tests.test_constructor.TestConstructorFromLogin object at 0x000001DE7E1A58D0>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"e428b3c0-fd1f-4cce-9e2f-b00a118101f9\")>\nmain_page = <pages.main_page.MainPage object at 0x000001DE7E3AD190>\n\n    @pytest.mark.usefixtures(\"ui_auth_user\")\n    @allure.title(\"Залогиненный пользователь может оформить заказ\")\n    def test_authorized_user_can_make_order(self, driver, main_page):\n        with allure.step(\"Проверка авторизации\"):\n            WebDriverWait(driver, 10).until(\n                lambda d: \"login\" not in d.current_url,\n                \"Пользователь не авторизован или страница не загрузилась\"\n            )\n        with allure.step(\"Открываем главную страницу\"):\n            main_page.open()\n            WebDriverWait(driver, 10).until(\n                EC.visibility_of_element_located(MainPageLocators.INGREDIENT_SECTION),\n                \"Секция ингредиентов не загрузилась\"\n            )\n        with allure.step(\"Добавляем ингредиенты\"):\n            main_page.add_bun_to_constructor()  # Используем существующий метод\n        with allure.step(\"Оформляем заказ\"):\n            main_page.make_order()\n>           order_number = WebDriverWait(driver, 15).until(\n                lambda d: main_page.get_order_number(),\n                \"Не удалось получить номер заказа\"\n            )\n\ntests\\test_constructor.py:145: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nvenv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:92: in until\n    value = method(self._driver)\ntests\\test_constructor.py:146: in <lambda>\n    lambda d: main_page.get_order_number(),\npages\\main_page.py:99: in get_order_number\n    return self.wait.until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"e428b3c0-fd1f-4cce-9e2f-b00a118101f9\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x000001DE7E3AAFC0>, message = ''\n\n    def until(self, method: Callable[[WebDriver], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\nvenv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:101: TimeoutException"}, "steps": [{"name": "Проверка авторизации", "status": "passed", "start": 1748199400570, "stop": 1748199401077}, {"name": "Открываем главную страницу", "status": "passed", "start": 1748199401077, "stop": 1748199401697}, {"name": "Добавляем ингредиенты", "status": "passed", "start": 1748199401697, "stop": 1748199401718}, {"name": "Оформляем заказ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:552:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\windw\\PycharmProjects\\Diplom\\Diplom_3\\tests\\test_constructor.py\", line 145, in test_authorized_user_can_make_order\n    order_number = WebDriverWait(driver, 15).until(\n        lambda d: main_page.get_order_number(),\n        \"Не удалось получить номер заказа\"\n    )\n  File \"C:\\Users\\windw\\PycharmProjects\\Diplom\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 92, in until\n    value = method(self._driver)\n  File \"C:\\Users\\windw\\PycharmProjects\\Diplom\\Diplom_3\\tests\\test_constructor.py\", line 146, in <lambda>\n    lambda d: main_page.get_order_number(),\n              ~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\windw\\PycharmProjects\\Diplom\\Diplom_3\\pages\\main_page.py\", line 99, in get_order_number\n    return self.wait.until(\n           ~~~~~~~~~~~~~~~^\n        EC.visibility_of_element_located(self.locators.ORDER_NUMBER)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ).text\n    ^\n  File \"C:\\Users\\windw\\PycharmProjects\\Diplom\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 101, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1748199401718, "stop": 1748199444090}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1748199400569, "stop": 1748199444092, "uuid": "60169192-f1e1-41e3-a907-4b9df50abafd", "historyId": "14c789deefb282f00679484ce56e0142", "testCaseId": "abc0047ddaa9cdb71f54c676c4cd3ed2", "fullName": "tests.test_constructor.TestConstructorFromLogin#test_authorized_user_can_make_order", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('ui_auth_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_constructor"}, {"name": "subSuite", "value": "TestConstructorFromLogin"}, {"name": "host", "value": "Gemini_78"}, {"name": "thread", "value": "19464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_constructor"}]}